# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/Terraform'
- task: PublishBuildArtifacts@1
  inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'terraform'
        publishLocation: 'Container'
  
- task: CmdLine@2
  inputs:
      script: |
        pip install virtualenv 
        virtualenv venv 
        ls -la /home/vsts/work/1/s/venv
        pip install wheel setuptools
- task: PythonScript@0
  inputs:
            scriptSource: 'inline'
            script: |
              import pandas as pd
              import urllib.request
              import io
              
              with urllib.request.urlopen('http://server:5000/get-artifact?path=dataframe.csv&run_uuid=75hf8234h9dj29jr943909') as f:
                  file = pd.read_csv(io.BytesIO(f.read()))
      